/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package estoque_pendente;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import ordem_producao.OrdemProducao;

/**
 *
 * @author Lenovo
 */
public class EstoquePendenteGUI extends javax.swing.JFrame {

    /**
     * Creates new form EstoquePendenteGUI
     */
    public EstoquePendenteGUI(OrdemProducao op) {
        initComponents();
        painel();
        this.op = op;
    }
    OrdemProducao op;
    
    
        //Criando painel
        JPanel pane = new JPanel();
        JTextField largura = new JTextField(5);
        JTextField metragem = new JTextField(5);

    public void painel(){
        JLabel Largura = new JLabel("Largura");
        JLabel Metragem = new JLabel("Metragem");
        //Adicionando componentes ao painel
        pane.add(Largura);
        pane.add(largura);
        pane.add(Metragem);
        pane.add(metragem);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_estoquePendente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_deleteEstoque = new javax.swing.JButton();
        btn_updateEstoque = new javax.swing.JButton();
        btn_addEstoque = new javax.swing.JButton();
        btn_confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque Pendente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tab_estoquePendente.setBackground(new java.awt.Color(255, 255, 255));
        tab_estoquePendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tab_estoquePendente.setForeground(new java.awt.Color(0, 0, 0));
        tab_estoquePendente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Largura", "Metragem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_estoquePendente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tab_estoquePendente.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane5.setViewportView(tab_estoquePendente);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Estoque Pendente");

        btn_deleteEstoque.setBackground(new java.awt.Color(255, 255, 255));
        btn_deleteEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excluir.png"))); // NOI18N
        btn_deleteEstoque.setText("Deletar Produto");
        btn_deleteEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteEstoqueActionPerformed(evt);
            }
        });

        btn_updateEstoque.setBackground(new java.awt.Color(255, 255, 255));
        btn_updateEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar (2).png"))); // NOI18N
        btn_updateEstoque.setText("Editar Produto");
        btn_updateEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateEstoqueActionPerformed(evt);
            }
        });

        btn_addEstoque.setBackground(new java.awt.Color(255, 255, 255));
        btn_addEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/adicionar.png"))); // NOI18N
        btn_addEstoque.setText("Adicionar Produto");
        btn_addEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addEstoqueActionPerformed(evt);
            }
        });

        btn_confirm.setBackground(new java.awt.Color(255, 255, 255));
        btn_confirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_confirm.setText("Confirmar");
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_updateEstoque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_deleteEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn_addEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_confirm)
                        .addGap(48, 48, 48)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_addEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_updateEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_deleteEstoque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(btn_confirm)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteEstoqueActionPerformed
        int selectedRow = -1;
        selectedRow = tab_estoquePendente.getSelectedRow();
        if(selectedRow >= 0){
            switch(JOptionPane.showConfirmDialog(null, "Deseja mesmo remover essa medida?","Remover medida",JOptionPane.YES_NO_OPTION)){
                case JOptionPane.YES_OPTION:
                    DefaultTableModel model = (DefaultTableModel) tab_estoquePendente.getModel();
                        model.removeRow(selectedRow);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Selecione uma medida");
        }
    }//GEN-LAST:event_btn_deleteEstoqueActionPerformed

    private void btn_updateEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateEstoqueActionPerformed
        
        int selectedRow = -1;
        selectedRow = tab_estoquePendente.getSelectedRow();
        if(selectedRow >= 0){
            largura.setText(String.valueOf(tab_estoquePendente.getValueAt(selectedRow, 0)));
            metragem.setText(String.valueOf(tab_estoquePendente.getValueAt(selectedRow, 1)));
            switch(JOptionPane.showConfirmDialog(null, pane,"Atualizar medida",JOptionPane.OK_CANCEL_OPTION)){
                case JOptionPane.OK_OPTION:
                    DefaultTableModel model = (DefaultTableModel) tab_estoquePendente.getModel();
                        try{
                            Object[] line = {Float.valueOf(largura.getText()),Float.valueOf(metragem.getText())};
                                       model.addRow(line);
                                       model.removeRow(selectedRow);

                        }catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(null, "Digite um valor numérico!\nColoque ponto no lugar da vírgula, se houver.");
                        }catch(Exception e){
                            e.printStackTrace();
                        }        
             
            }
            
        } else {
            JOptionPane.showMessageDialog(null,"Selecione uma medida");
        }
       
    }//GEN-LAST:event_btn_updateEstoqueActionPerformed

    private void btn_addEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addEstoqueActionPerformed
        largura.setText("");
        metragem.setText("");
        //Exibindo painel em um JOptionPane
        switch(JOptionPane.showConfirmDialog(null,pane,"Correia Estoque Pendente",JOptionPane.OK_CANCEL_OPTION)){
            case JOptionPane.OK_OPTION:
                DefaultTableModel model = (DefaultTableModel) tab_estoquePendente.getModel();
                    try{
                        Object[] line = {Float.valueOf(largura.getText()),Float.valueOf(metragem.getText())};
                            model.addRow(line);
                    }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(null, "Digite um valor numérico!\nColoque ponto no lugar da vírgula, se houver");
                    }catch(Exception e){
                        e.printStackTrace();
                    }      
        }
        
        
    }//GEN-LAST:event_btn_addEstoqueActionPerformed

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        float areaTotalEst = 0;
        List<EstoquePendente> listEstPend = new ArrayList<>();
        for(int i = 0; i < tab_estoquePendente.getRowCount(); i++){
            EstoquePendente estoquePendente = new EstoquePendente();
            estoquePendente.setId_op(op.getId());
            estoquePendente.setCategoria(op.getCategoria());
            estoquePendente.setLonas(op.getLonas());
            float larg = Float.parseFloat(String.valueOf(tab_estoquePendente.getValueAt(i, 0)));
            estoquePendente.setLargura(larg);
            float met = Float.parseFloat(String.valueOf(tab_estoquePendente.getValueAt(i, 1)));
            estoquePendente.setMetragem(met);
                listEstPend.add(estoquePendente);
                
                areaTotalEst+=larg*met;
                
        }
        if(areaTotalEst <= op.getLarguraTecido() * op.getMetragemTecido()){
            
        } else {
            JOptionPane.showMessageDialog(null, "Medidas não batem, favor conferir!");
        }
        
    }//GEN-LAST:event_btn_confirmActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addEstoque;
    private javax.swing.JButton btn_confirm;
    private javax.swing.JButton btn_deleteEstoque;
    private javax.swing.JButton btn_updateEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tab_estoquePendente;
    // End of variables declaration//GEN-END:variables
}
