/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.EstoqueDAO;
import dao.ProdutoDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estoque;
import modelo.Produto;


/**
 *
 * @author Lenovo
 */
public class CEstoqueGUI extends javax.swing.JFrame {

    /**
     * Creates new form CEstoqueGUI
     */
    public CEstoqueGUI() {
        initComponents();
        tabela();
    }

    
    public void tabela(){
        EstoqueDAO estoquedao = new EstoqueDAO();
        DefaultTableModel modelo = (DefaultTableModel) tab_estoque.getModel();
        
        
        while(tab_estoque.getModel().getRowCount() > 0 ){
            ((DefaultTableModel) tab_estoque.getModel()).removeRow(0);
        }
        
        List<Estoque> estoqueList = estoquedao.selectEstoque();
        for (Estoque estoque : estoqueList) {
            
            Object[] line = {estoque.getId(), estoque.getCategoria(), estoque.getLonas(), estoque.getLargura(), estoque.getMetragem()};
            modelo.addRow(line);
            
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_estoque = new javax.swing.JTable();
        add_estoque = new javax.swing.JButton();
        upd_estoque = new javax.swing.JButton();
        del_est = new javax.swing.JButton();
        est_pendente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque Correias");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tab_estoque.setBackground(new java.awt.Color(255, 255, 255));
        tab_estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tab_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Lonas", "Largura", "Metragem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tab_estoque);

        add_estoque.setBackground(new java.awt.Color(255, 255, 255));
        add_estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add_estoque.setText("Adicionar");
        add_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_estoqueActionPerformed(evt);
            }
        });

        upd_estoque.setBackground(new java.awt.Color(255, 255, 255));
        upd_estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        upd_estoque.setText("Editar");
        upd_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upd_estoqueActionPerformed(evt);
            }
        });

        del_est.setBackground(new java.awt.Color(255, 255, 255));
        del_est.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        del_est.setText("Excluir");
        del_est.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_estActionPerformed(evt);
            }
        });

        est_pendente.setBackground(new java.awt.Color(204, 204, 204));
        est_pendente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        est_pendente.setText("Estoque Pendente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(add_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(upd_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(del_est, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(est_pendente))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upd_estoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(del_est, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(est_pendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void add_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_estoqueActionPerformed
        EstoqueDAO estoquedao = new EstoqueDAO();
        estoquedao.insertEstoque(estoquedao.pane(null,null,null,null));
        JOptionPane.showMessageDialog(null,"Correia adicionada com sucesso!");
        tabela();
        
    }//GEN-LAST:event_add_estoqueActionPerformed

    private void del_estActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_estActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = tab_estoque.getSelectedRow();
        if(linhaSelecionada >=0){
            
            switch(JOptionPane.showConfirmDialog(null,"Deseja mesmo excluir essa correia?","Aviso",JOptionPane.YES_NO_OPTION)){
                case JOptionPane.YES_OPTION:    
                EstoqueDAO estoquedao = new EstoqueDAO(); 
                int id = (int) tab_estoque.getValueAt(linhaSelecionada, 0);
                estoquedao.deleteEstoque(id);
                tabela();
                
            break;
            }
            
        } else {
            JOptionPane.showMessageDialog(null,"Selecione a correia que deseja excluir");
        }
        
    }//GEN-LAST:event_del_estActionPerformed

    private void upd_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upd_estoqueActionPerformed
        EstoqueDAO estoquedao = new EstoqueDAO();
        
        int linhaSelecionada = -1;
        linhaSelecionada = tab_estoque.getSelectedRow();
        if(linhaSelecionada >=0){
            
            int id = (int) tab_estoque.getValueAt(linhaSelecionada,0);
            String categoria = (String) tab_estoque.getValueAt(linhaSelecionada,1);
            String lonas = (String) String.valueOf(tab_estoque.getValueAt(linhaSelecionada,2));
            String largura = (String) String.valueOf(tab_estoque.getValueAt(linhaSelecionada,3));
            String metragem = (String) String.valueOf(tab_estoque.getValueAt(linhaSelecionada,4));
            
            estoquedao.updadeEstoque(estoquedao.pane(categoria, lonas, largura, metragem), id);
            tabela();
            
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione a correia que deseja editar");
        }
        
        
        
        
    }//GEN-LAST:event_upd_estoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CEstoqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CEstoqueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_estoque;
    private javax.swing.JButton del_est;
    private javax.swing.JButton est_pendente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tab_estoque;
    private javax.swing.JButton upd_estoque;
    // End of variables declaration//GEN-END:variables
}
